### ISSUE TITLE
Tried to edit tmTheme, and found that entity meanings (naming?) messed/shifted.

### ISSUE THREAD

**Issue by nugged** [Blaizer/ModernPerl-sublime#19]
Items class such like "Variables" (and they right interpreted with old Perl highlight):

![Perl](https://cloud.githubusercontent.com/assets/295324/7219910/72809aa0-e6be-11e4-85ef-d97a0bb5cbe4.JPG)

In ModernPerl it looks shifted:

![ModernPerl](https://cloud.githubusercontent.com/assets/295324/7219911/74da5002-e6be-11e4-82bd-a7d26e5773cd.JPG)

Variables in quoted strings get's highlighted, but outside "my" instead of variables get highlighted.
Is that can be easily corrected or that "base thing" which not so easy to change?
Is there any quick-and-dirty workaround for it at least so I can adapt tmTheme myself? 

I just downloaded few different color schemes to test... seems it's not schemes trouble, from here:
https://tmtheme-editor.herokuapp.com/#/theme/Atom%20Dark
(I manually changed background for variables to be more distinctive).

**Comment by Blaizer** [comment]
It's trivial to add to your theme, yes. Find the part that styles the `variable` scope, and add a comma and then the scope `punctuation.definition.var.perl`. Something like this:

```
<dict>
	<key>name</key>
	<string>Variable</string>
	<key>scope</key>
	<string>variable,punctuation.definition.var.perl</string>
	<key>settings</key>
	<dict>
		<key>foreground</key>
		<string>#c8c5ff</string>
	</dict>
</dict>
```
