### ISSUE TITLE
substitutions with eval

### ISSUE THREAD

**Issue by ambs** [Blaizer/ModernPerl-sublime#20]
The second part of a substitution that has the 'e' modifier should be colored as Perl code and not as a string.

Thanks.

**Comment by Blaizer** [comment]
This isn't really possible with the way the syntax definition works. In short, the nested code will often "spill out" of the second part of the substitution, any time there's something the slightest bit weird in the substitution.

Also, looking ahead for the `/e` isn't even possible in cases where the regex is multiline. That's just the way the syntax definition works. Same reason I can't and won't ever be able to support `/x`.

**Comment by ambs** [comment]
It is a shame. Emacs does it, as so does vim. :-(

**Comment by Blaizer** [comment]
If you wanna see the "spill out" problem yourself, write this code into a ModernPerl source file.

```
<<HTML;
<asd
HTML
>
# should be perl here
<!-- but yuck, it's actually HTML -->
```

**Comment by ambs** [comment]
Note I was not criticizing or doubting your work. Just sad :-)
