### ISSUE TITLE
Don't work comment strings

### ISSUE THREAD

**Issue by woodcrust** [Blaizer/ModernPerl-sublime#23]
Sorry. I know English very bad... I disabled Package: Perl for default highlighting syntax "modernperl" and I was opening files with interpreter type: #!/usr/bin/perl.  But after disable standart Package: Perl and reboot sublime, commenting strings is don't  working.

**Comment by catzilla-007** [comment]
To clarify woodcrust's issue:

On the default perl package, using CTRL+/ makes a comment.
but when using ModernPerl, it doesn't do anything.
I also experienced this on sublime text 2

**Comment by woodcrust** [comment]
Thank you :)
