### ISSUE TITLE
Can this be used for terminal highlighting? 

### ISSUE THREAD

**Issue by rocky** [Blaizer/ModernPerl-sublime#24]
This is more a series of question than an issue. I'm using [Syntax::Highlight::Perl::Improved](https://metacpan.org/pod/Syntax::Highlight::Perl::Improved) for formatting Perl code inside [Devel::Trepan](https://metacpan.org/pod/Devel::Trepan). Could this be used as a reasonable alternative?  Specifically, does it handle output to a terminal which handles ANSI terminal escape codes? 

Aside from the ability to handle Perl's difficult-to-parse syntax which you do handle, here are some features I think that are nice to have in a syntax formatter. 

1. Ability to apply someone's pre-determined color style. See for example [python pygments styles]( http://pygments.org/docs/styles/). Once the general mechanism is there one can find style names and colors setting many places.

2. In addition or instead of this, having two profiles, one for a predominantly dark background or a predominantly light background is useful. And within a style if that is there, noting which is which is also useful. 

3. Having a way to customize a particular attribute. For example, I was at a talk where David Golden said he changed just comments to red because he wanted them to stick out.

**Comment by Blaizer** [comment]
The syntax highlighter sublime text use is taken from textmate, which is open-soure. I can give you a link to the textmate repo, but that's about all I can help you with.

https://github.com/textmate/textmate
